### ISSUE TITLE
Mutation List Will not Work.

### ISSUE THREAD

**Issue by Dviros** [bf/solarleaks-crawler#1]
Hi Ben,
Afraid the great mutation list you created might not work as it's all in uppercase and the FQDN is case sensitive,
For example:
http://solarleaks.net/msft.tgz.enc
Not equal to
http://solarleaks.net/MSFT.tgz.enc

Suggest on changing it all to lowercase.

Thanks
D

**Comment by Dviros** [comment]
Can be seen here.
https://github.com/bf/solarleaks-crawler/pull/2

**Comment by bf** [comment]
Thanks for creating the issue & PR. But I cannot reproduce the bug. For me, when running `./crawl-stock-ticker-symbols.sh` the `tr "[:upper:]" "[:lower:]"` will make everything lowercase anyways. So why is this needed?

**Comment by Dviros** [comment]
🤦 
Missed that important function. Sorry for the noise, will close it down.
Thanks

**Comment by bf** [comment]
@Dviros don't worry, thanks for investigating the issue :-)
